"""add_reconciliation_tables

Revision ID: d4a6d507b7cf
Revises: 1d1f963a8651
Create Date: 2025-10-11 21:03:16.548961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4a6d507b7cf'
down_revision: Union[str, None] = '1d1f963a8651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
